
from app import db, Place, app

# with app.app_context():
    # db.drop_all()


with app.app_context() as f:
    db.create_all()
    place1 = Place(name="Lalbagh Botanical Garden", budget=50, age_rating="All ages", location="Lalbagh Road", image="https://thumbs.dreamstime.com/b/lalbagh-park-bangalore-city-night-scene-india-49466419.jpg")
    place2 = Place(name="Wonderla", budget=1016, age_rating="7-45", location="Mysore RoadY", image="https://i.ytimg.com/vi/yp3B7hdot_U/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLDihT4YF-7qpCxy2Z_DfQbwpNmqIA")
    place3 = Place(name="Cubbon Park", budget=50, age_rating="10-40", location="New Jersey", image="https://live.staticflickr.com/5231/5890174957_7e9d8622fa_b.jpg")
    place4 = Place(name="Snow City", budget=0, age_rating="10-40", location="", image="https://example.com/six_flags.jpg")
    place5 = Place(name="UB City", budget=0, age_rating="10-40", location="", image="https://example.com/six_flags.jpg")
    place6 = Place(name="Orion Mall", budget=0, age_rating="10-40", location="", image="https://example.com/six_flags.jpg")
    place7 = Place(name="Forum Mall", budget=0, age_rating="10-40", location="", image="https://example.com/six_flags.jpg")
    place8 = Place(name="Mantri Mall", budget=0, age_rating="10-40", location="", image="https://example.com/six_flags.jpg")
    place9 = Place(name="Vega City", budget=0, age_rating="10-40", location="", image="https://example.com/six_flags.jpg")
    place10 = Place(name="Commercial Street", budget=0, age_rating="10-40", location="", image="https://example.com/six_flags.jpg")
    place11= Place(name="Church Street", budget=0, age_rating="10-40", location="", image="https://example.com/six_flags.jpg")
    place12= Place(name="M.G. Road", budget=0, age_rating="10-40", location="", image="https://example.com/six_flags.jpg")
    place13= Place(name="Brigade Road", budget=0, age_rating="10-40", location="", image="https://example.com/six_flags.jpg")
    place14= Place(name="ISKCON Temple", budget=0, age_rating="10-40", location="", image="https://example.com/six_flags.jpg")
    place15= Place(name="Bannerghatta National Park", budget=0, age_rating="10-40", location="", image="https://example.com/six_flags.jpg")
    place16 = Place(name="Phoenix Marketcity", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place17= Place(name="Bangalore Palace", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place18= Place(name="Visvesvaraya Industrial & Technological Museum", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place19= Place(name="Bull Temple", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place20= Place(name="Play Aren", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place21= Place(name="Indian Music Experience Museum", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place22= Place(name="Jayanagar Shopping Complex", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place23= Place(name="Sree Surya Narayana Swamy Temple", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place24= Place(name="Ragigudda Sri Prasanna Anjaneyaswamy Temple", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place25= Place(name="Nandi Hills", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place26= Place(name="Vidhana Soudha", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place27= Place(name="Tipu Sultan's Summer Palace", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place28= Place(name="Jawaharlal Nehru Planetarium", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place29= Place(name="Innovative Film City", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place30= Place(name="Art of Living International Centre", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place31= Place(name="Ulsoor Lake", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place32= Place(name="National Gallery of Modern Art", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place33= Place(name="Shiva Temple", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place34= Place(name="St Mary's Basilica", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place35= Place(name="Chunchi Falls", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place36= Place(name="Fun World", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place37= Place(name="HAL Aerospace Museum", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place38= Place(name="Pearl Valley", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place39= Place(name="Jakkur Aerodome", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place40= Place(name="Devanahalli Fort", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place41= Place(name="Ranga Shankara", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place42= Place(name="Smaaash", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place43= Place(name="Bangalore Aquarium", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place44= Place(name="Maha Bodhi Society Temple", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place45= Place(name="Devanahalli Fort", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place46= Place(name="Ragigudda Anjaneya Temple", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place47= Place(name="Venkatappa Art Gallery", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place48= Place(name="Grover Zampa Vineyards", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place49= Place(name="Soma Vine Village", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place50= Place(name="Heritage Winery", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place51= Place(name="Big Banyan Tree", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place52= Place(name="Indian Institute of Cartoonists", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place53= Place(name="Bangalore Fort", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place54= Place(name="Karnataka Chitrakala Parishath", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place55= Place(name="Sublime Galleria", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place56= Place(name="Bangalore Turf Club", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place57= Place(name="Devarayanadurga", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place58= Place(name="Doddamakali", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place59= Place(name="Manchanabele Dam", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place60= Place(name="Skandagiri", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place61= Place(name="Bilikal Rangaswamy Betta", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place62= Place(name="Avalabetta", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place63= Place(name="Indira Gandhi Musical Fountain Park", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place64= Place(name="Guhantara Resort", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place65= Place(name="Area 83", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place66= Place(name="Eagleton- The Golf Resort", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place67= Place(name="VV Puram Food Street", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place68= Place(name="Big Brewsky", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place69= Place(name="The Pumphouse", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place70= Place(name="Paintball X", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place71= Place(name="Hard Rock Cafe", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place72= Place(name="Roxie", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place73= Place(name="Oia", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place74= Place(name="Third Wave Cafe", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place75= Place(name="Uru Brewpark", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place76= Place(name="Pangeo", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place77= Place(name="Mykos", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place78= Place(name="Chianti", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place79= Place(name="The Palms", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place80= Place(name="Paris Panini", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place81= Place(name="The Pizza Bakery", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place82= Place(name="Brik Oven", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place83= Place(name="Pizza Hut", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place84= Place(name="Dominos", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place85= Place(name="Subway", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place86= Place(name="California Burrito", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place87= Place(name="Taco Bell", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place88= Place(name="Sky Laser Tag", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place89= Place(name="Krispy Kreme", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place90= Place(name="Bastian", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place91= Place(name="Church Street SOCIAL", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place92= Place(name="Amoeba", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place93= Place(name="McDonald's", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place94= Place(name="One8 Commune", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place95= Place(name="Cafe Noir", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place96= Place(name="Cafe Coffee Day", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place97= Place(name="Take A Break", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place98= Place(name="Taproom", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place99= Place(name="Hakuna Matata", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place100= Place(name="Brahma Brews", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place101= Place(name="Indian Biere House", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place102= Place(name="BLR Brewing Co", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place103= Place(name="Ironhill", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place104= Place(name="STORIES", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place105= Place(name="The Grid", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place106= Place(name="DYU Art Cafe", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place107= Place(name="The Hole In The Wall Cafe", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place108= Place(name="TORQ03", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place109= Place(name="Loco Bear", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")
    place110= Place(name="Breakout", budget=50, age_rating="10-40", location="New Jersey", image="https://example.com/six_flags.jpg")

    db.session.add_all([place1, place2, place3, place4, place5, place6, place7, place8, place9, place10, place11, place12, place13, place14, place15, place16, place17, place18, place19, place20, place21, place22, place23, place24, place25, place26, place27, place28, place29, place30, place31, place32, place33, place34, place35, place36, place37, place39, place40, place41, place42, place43, place44, place45, place46, place47, place48, place49, place50, place51, place52, place53, place54, place55, place56, place57, place58, place59, place60, place61, place62, place63, place64, place65, place66, place67, place68, place69, place70, place71, place72, place73, place74, place75, place76, place77, place78, place79, place80, place81, place82, place83, place84, place85, place86, place87, place88, place89, place90, place91, place92, place93, place94, place95, place96, place97, place98, place99, place100, place101, place102, place103, place104, place105, place106, place107, place108, place109, place110])

    db.session.commit()

    